name: Deploy Image To Registry
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Install Dependencies
        working-directory: ./app
        run: npm ci
      - name: Run Tests
        working-directory: ./app
        run: npm test
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: michealnaita/donation-bot:latest
