name: Testing
on:
  push:
    branches: [main]
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Install Dependencies
        working-directory: ./app
        run: npm ci
      - name: Run Tests
        working-directory: ./app
        run: npm test
